import { Flame, Trash } from "../lib/icons.jsx";

// Today — neon coach layout: progress arc, compact metrics, insight, and meal timeline.
export default function Today({ totals, goal, remaining, entries, onDelete, onSelect, dayLabel, isToday, onToday, onPrev, onNext, canPrev, canNext }) {
  const pct = Math.min(1, Math.max(0, Number(totals.protein) / Math.max(1, Number(goal))));
  const dash = Math.round(410 * (1 - pct));
  return <div className="today-neon">
    <div className="today-daybar"><DayArrow chevron="›" label="יום קודם" disabled={!canPrev} onClick={onPrev} /><div className="today-daycenter"><div className="today-daylabel">{dayLabel}</div>{!isToday && <button className="back-today" onClick={onToday}>היום</button>}</div><DayArrow chevron="‹" label="יום הבא" disabled={!canNext} onClick={onNext} /></div>
    <section className="hero-neon"><div className="hero-glow" /><div className="hero-kicker">יעד חלבון יומי</div><div className="arc-wrap"><svg viewBox="0 0 220 140" aria-hidden="true"><path d="M24 120 A86 86 0 0 1 196 120" fill="none" stroke="#143a30" strokeWidth="15" strokeLinecap="round" /><path d="M24 120 A86 86 0 0 1 196 120" fill="none" stroke="#39e6b2" strokeWidth="15" strokeLinecap="round" strokeDasharray="410" strokeDashoffset={dash} style={{ filter: "drop-shadow(0 0 8px rgba(57,230,178,.5))", transition: "stroke-dashoffset .5s ease" }} /></svg><div className="arc-value"><strong>{totals.protein}</strong><span>/ {goal} גרם</span></div></div><div className="hero-remaining">{remaining > 0 ? `נשארו ${remaining} גרם` : "היעד הושג"} · {totals.pctLabel} מהיעד</div></section>
    <section className="metric-row"><div className="metric"><div className="metric-value protein">{totals.protein}</div><div className="metric-label">גרם חלבון</div><div className="metric-sub">מתוך {goal}</div><div className="metric-bar"><i style={{ width: `${pct * 100}%`, background: "#39e6b2" }} /></div></div><div className="metric-divider" /><div className="metric"><div className="metric-value calories">{totals.calories}</div><div className="metric-label"><Flame size={14} /> קלוריות</div><div className="metric-sub">מספר רץ</div><div className="metric-bar"><i style={{ width: "42%", background: "#25b9ff" }} /></div></div></section>
    <section className="insight-neon"><div className="insight-icon">✦</div><div><strong>{totals.protein ? "אתה בדרך הנכונה." : "מתחילים בקטן."}</strong><span>כל בחירה קטנה היום מקרבת אותך ליעד.</span></div></section>
    <div className="entries-head"><strong>מה אכלת</strong><span>{totals.count} פריטים</span></div>
    {entries.length === 0 ? <div className="empty-neon">עדיין לא הוספת ארוחות היום</div> : <div className="meal-list">{entries.map((e, i) => <div key={e.id} className="meal-row" onClick={() => onSelect(e)} role="button" tabIndex={0} aria-label={`פרטי ${e.name}`}><div className="meal-dot" style={{ background: i % 2 ? "#25b9ff" : "#39e6b2" }} /><div className="meal-copy"><strong>{e.name}</strong><span>{e.sub}</span></div><div className="meal-macros"><b>{e.protein}g</b><small>{e.calories} קל'</small></div><button className="h-del meal-delete" aria-label="מחק רישום" onClick={(ev) => { ev.stopPropagation(); onDelete(e.id); }}><Trash size={15} /></button></div>)}</div>}
  </div>;
}

function DayArrow({ chevron, label, disabled, onClick }) { return <button className="day-arrow-neon" onClick={onClick} disabled={disabled} aria-label={label}>{chevron}</button>; }
